<?php

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\server\hook\integration;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="winwin.event_bus.EventBusObj")
 */
interface EventBusServant
{
    /**
     * @TarsParameter(name = "topic", type = "string")
     * @TarsParameter(name = "event", type = "string")
     * @TarsParameter(name = "payload", type = "string")
     * @TarsReturnType(type = "string")
     *
     * @param string $topic
     * @param string $event
     * @param string $payload
     * @return string
     */
    public function publish($topic, $event, $payload);

    /**
     * @TarsParameter(name = "topic", type = "string")
     * @TarsParameter(name = "event", type = "string")
     * @TarsParameter(name = "payload", type = "string")
     * @TarsReturnType(type = "bool")
     *
     * @param string $topic
     * @param string $event
     * @param string $payload
     * @return bool
     */
    public function publishNow($topic, $event, $payload);

}
